const express = require("express");
const auth = require("../routes/auth");
const users = require("../routes/users");
const courses = require("../routes/courses");
const clients = require("../routes/clients");
const testimonials = require("../routes/testimonials");
const events = require("../routes/events");
const vision = require("../routes/vision");
const mission = require("../routes/mission");
const privacy = require("../routes/privacy");
const terms = require("../routes/terms");
const services = require("../routes/services");
const caseStudy = require("../routes/case");
const teams = require("../routes/teams");
const about = require("../routes/about");
const email = require("../routes/email");
const upload = require("../routes/upload");

const error = require("../middleware/error");
module.exports = function (app) {
  app.use(express.json());
  app.use("/api/auth", auth);
  app.use("/api/users", users);
  app.use("/api/events", events);
  app.use("/api/clients", clients);
  app.use("/api/courses", courses);
  app.use("/api/testimonials", testimonials);
  app.use("/api/mission", mission);
  app.use("/api/vision", vision);
  app.use("/api/privacy", privacy);
  app.use("/api/terms", terms);
  app.use("/api/services", services);
  app.use("/api/case", caseStudy);
  app.use("/api/teams", teams);
  app.use("/api/about", about);
  app.use("/api/email", email);
  app.use("/api/upload", upload);
  app.use(error);
};
